GDB-5294 Implement window messaging service to receive language string
Ontotext-AD/mapping-ui pull request #215
Opened 2021-01-06 15:19 UTC by yordanalexandrov

Implemented service to handle massages posted from parent window

2021-01-06 17:07 UTC, svilenvelikov approved these changes

2021-01-06 17:08 UTC, svilenvelikov commented
LGTM, but just check why the lint has failed!

2021-01-07 06:01 UTC, teodossidossev commented
lint issue - 'MessageType' is defined but never used

2021-01-07 06:10 UTC, teodossidossev requested changes

2021-01-07 06:10 UTC, teodossidossev commented on src/app/services/window-message-handling.service.ts
> +  subscribeToWindowParentMessageEvent() {
Please unsubscribe also. 
If it was a standalone application, this code is OK, because closing it will destroy the listener. The problem here is that the application is loaded in an iframe, and the listener will continue to live after closing the mapper.
Fire an event on destroy a component like the header or another always living one, and use it as event to unsubscribe.

2021-01-07 06:17 UTC, teodossidossev commented on src/app/services/window-message-handling.service.ts
> +  subscribeToWindowParentMessageEvent() {
You can add a unsubscribe method to the interface for further reminder

2021-01-07 06:31 UTC, yordanalexandrov commented on src/app/services/window-message-handling.service.ts
> +  subscribeToWindowParentMessageEvent() {
Well actually, I did test it and could not find a case where the subscription remains.
I will unsubscribe it just in case I missed something.

2021-01-07 06:32 UTC, yordanalexandrov commented on src/app/services/window-message-handling.service.ts
> +  subscribeToWindowParentMessageEvent() {
What interface?

2021-01-07 07:21 UTC, yordanalexandrov commented on src/app/services/window-message-handling.service.ts
> +  subscribeToWindowParentMessageEvent() {
As it turned out, upon exiting the mapping-ui, the refine framework closes the dialog completely and all listeners are removed.

2021-01-07 07:22 UTC, teodossidossev approved these changes

2021-01-07 07:22 UTC, teodossidossev commented on src/app/services/window-message-handling.service.ts
> +  subscribeToWindowParentMessageEvent() {
Turns out that the butterfly framework takes care to destroy everything, so you can leave it as it is.

2021-01-07 07:44 UTC, merged